#!/usr/bin/env bash
#Bash script that displays: "Done"
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM sign
trap "echo I am invincible!!!" SIGTERM
/**auth-omidoyin**/
while 'true'
do
	echo "To infinity and beyond"
	sleep 2
done
