#!/usr/bin/env bash
# This script is displaying "Best School" and "Hi" "Done

i=0

while [ $i -lt 10 ]
do
    echo "Best School"
    if ((i == 8))
    then
        echo "Hi"
    if
    i=$((i+1))
done
